services:

  zit-data:
    image: zit-data:latest
    volumes:
      - esdata1:/volume-data/:rw

  elasticsearch:
    container_name: zit-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw   

  web-api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile

volumes:
  esdata1:
    driver: local